CREATE TABLE Pessoas (
    Id INT PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Cpf NVARCHAR(14) NOT NULL,
    Sexo INT NOT NULL,
    EstadoCivil INT NOT NULL,
    DataNascimento DATE NOT NULL,
    OndeTrabalha NVARCHAR(100),
    Cargo NVARCHAR(50),
    Pais NVARCHAR(50) NOT NULL,
    Estado NVARCHAR(2) NOT NULL,
    Cidade NVARCHAR(50) NOT NULL,
    CEP NVARCHAR(9) NOT NULL,
    Logradouro NVARCHAR(100),
    Numero NVARCHAR(10),
    Complemento NVARCHAR(50),
    Bairro NVARCHAR(50),
    Telefone NVARCHAR(15) NOT NULL,
    Vinculo INT NOT NULL,
    Ministerio NVARCHAR(100),
    DataCadastro DATETIME NOT NULL,
    Ativo BIT NOT NULL,
    Batizado INT NOT NULL
);
